### ISSUE TITLE
PPI network from Gordon

### ISSUE THREAD

**Issue by jvfe** [lubianat/wikidata_covid19#1]
Oi, Tiago, vi que tu adicionou o paper do Gordon das redes PPI do Corona, você também planeja integrar os dados de interação do paper na wikidata? [Esses](https://www.ndexbio.org/#/network/5d97a04a-6fab-11ea-bfdc-0ac135e8bacf)

Não sei se esses dados tem uma licença que impeça-os de serem integrados, mas caso não tenham eu posso conciliar as proteínas e ligar elas pelo "physically interacts with". Ainda não sei como seria o modelo para representar interações proteína-proteína na wikidata, mas isso pareceu o mais lógico. O que acha?

**Comment by lubianat** [comment]
Show, é uma ótima, eu tava caminhando para fazer justamente isso a partir
dos dados já curados pelo BioGRID.

Aqui no repo eu coloquei a tabela, falta só reconciliar com o Wikidata. Tem
uns desafios, tipo reconciliar artigos que são referência (pq tem mais
coisa além do Gordon) e fazer o match das proteínas.

Eu tou animado pra fazer isso, então corre o risco da gente dobrar esforço.
Mas se quiser fazer também, manda bala!




Em dom, 19 de abr de 2020 17:53, João Vitor <notifications@github.com>
escreveu:

**Comment by jvfe** [comment]
Po, massa, cara. Se tu já ia fazer esse eu não vou te empatar kkkk, o que você quer dizer com artigos que são referência? Que  qualquer coisa posso ir integrando dados dessas outras fontes.

**Comment by lubianat** [comment]
Fala, @jvfe , já fiz a migração dos dados do Gordon! Não todos, pq algumas proteínas que eles reportaram não estão no Uniprot e, consequentemente, não foram modeladas no Wikidata ainda.

Do lado biológico tem muita coisa pra fazer! Só é difícil formalizar o que precisa rs. Tava caçando uns datasets prontos para migrar. Duas coisas que vale a pena dar uma olhada:

- https://www.wikidata.org/wiki/Wikidata:WikiProject_COVID-19/Automation

(vale até adicionar o que estamos fazendo de automação aqui)

- https://www.covid19dataportal.org/ aqui tem vários datasets interessantes. Vou dar uma caçada naqueles que podem ser bacanas para covid. 

De forma geral, a WIkidata ainda precisa de muuuita coisa. Por exemplo , tem mt mais informação de PPI na Wikipedia em ingles que na Wikidata.

**Comment by jvfe** [comment]
Massa! Por coincidência, também achei esse dataset do github e tava dando uma olhada nele no diretorio /worldwide_data/src. Parece bem simples de automatizar com o dicionário que eu já tenho. 

Só tive dúvida de como estruturar a referência, pq eles agregam os dados de vários cantos porém o dado final é o tratado por eles (do [datahubio](https://datahub.io/core/covid-19)), não achei uma situação parecida na wikidata de como proceder. O que você acha?

Vou dar uma buscada nesses outros datasets também, valeu pela dica!

**Comment by lubianat** [comment]
Cara, é uma boa pergunta, e algo bem em aberto. Eu faria essas coisas:
1 - citar a URL do repositório pela propriedade Reference URL mesmo, com a
data e horário de consulta.
2 - Perguntar na página de discussões do projeto (e explicar um pouco a
ideia)  https://www.wikidata.org/wiki/Wikidata_talk:WikiProject_COVID-19
3 - Elaborar um  bot request (
https://www.wikidata.org/wiki/Wikidata:Bot_requests)

Atualizar as páginas automaticamente sem passar pelo bot request é
tranquilo tb, até pq é uma questão de emergência, aí a discussão vai
rolando enquanto o bot já tá em funcionamento.





Tiago Lubiana,
MSc in Bioinformatics, University of São Paulo
*Computational Systems Biology Laboratory (CSBL)*
