### ISSUE TITLE
Format change - State data from Brazil

### ISSUE THREAD

**Issue by jvfe** [lubianat/wikidata_covid19#5]
(in portuguese due to being a local issue)

Hoje o site do ministério da saúde mudou totalmente a estrutura do dado que estavam fornecendo no site deles. Agora além de ser um xlsx (formato aberto pra quê né?), os dados parecem estar a nível de município/ou região, então o código tem que ser inteiramente adaptado. 

~Tô sem internet estável por enquanto então não sei se meus commits vão subir, mas pode ir trabalhando nisso também se tiver tempo @lubianat . Por hoje não vai dar pra submeter o dado pra wikidata, mas vou tentar deixar tudo resolvido pra amanhã.~

**Comment by jvfe** [comment]
Acredito que já consegui restaurar a funcionalidade que tinha antes com os csvs.

Um ponto positivo a se considerar com o novo formato do dado é ampliar os mapas de distribuição para mais estados, visto que agora se tem mais dado a nível de município. Porém ainda não verifiquei a qualidade/precisão desse dado.

**Comment by lubianat** [comment]
De fato, tem essa vantagem! E compartilho o incômodo com .xlsx.

Não consegui olhar ontem à noite, mas valeu por avisar.
Eu chutaria que está desatualizado em comparação com os dados das
secretarias, mas um mapa um pouco desatualizado é melhor que nenhum mapa.
Acho que vale a pena sim.

**Comment by jvfe** [comment]
Depois dá uma olhada nesse último commit, acho que é uma forma pra automatizar a criação de mapas pra todos os estados brasileiros, a partir do novo dado fornecido pelo Min. Ligando com o script do get_csv (que agora deveria se chamar get excel kkkk) e com suas funções pra submeter pro commons, acho que dá pra automatizar totalmente.

**Comment by lubianat** [comment]
massa! vou dar uma olhada amanhã. 
Vou ver tbm se consigo já colocar o Wikidata Integrator rolando no pano de fundo, que aí pula a necessidade de API do quickstatements e complicações relacionadas. 

Show!

**Comment by lubianat** [comment]
Consegui rodar aqui hoje, show!. Amanhã vou ver se consigo adicionar a integração com o Commons e o QuickStatements.
